# Enhanced weapon skin mappings with correct collection and rarity data
# Generated by CS2 Trade Up Calculator weapon skin extraction tool

# These mappings include proper collection and rarity information for popular CS2 weapon skins
ENHANCED_WEAPON_SKIN_MAPPINGS = {
    # AK-47 Skins
    "AK-47 | Aquamarine Revenge": ("Falchion", "Covert"),
    "AK-47 | Asiimov": ("Operation Hydra", "Covert"),
    "AK-47 | Bloodsport": ("Spectrum", "Covert"),
    "AK-47 | Case Hardened": ("Arms Deal", "Classified"),
    "AK-47 | Fire Serpent": ("Operation Bravo", "Covert"),
    "AK-47 | Frontside Misty": ("Shadow", "Classified"),
    "AK-47 | Inheritance": ("Revolution", "Classified"),
    "AK-47 | Legion of Anubis": ("Anubis", "Covert"),
    "AK-47 | Neon Rider": ("Spectrum", "Classified"),
    "AK-47 | Phantom Disruptor": ("Broken Fang", "Classified"),
    "AK-47 | Point Disarray": ("Chroma 3", "Classified"),
    "AK-47 | Redline": ("Huntsman", "Classified"),
    "AK-47 | Slate": ("Chroma 2", "Restricted"),
    "AK-47 | The Empress": ("Spectrum 2", "Covert"),
    "AK-47 | Vulcan": ("Huntsman", "Covert"),
    "AK-47 | Wasteland Rebel": ("Phoenix", "Classified"),

    # M4A4 Skins
    "M4A4 | Howl": ("Huntsman", "Contraband"),
    "M4A4 | Asiimov": ("Operation Phoenix", "Covert"),
    "M4A4 | Dragon King": ("Cache", "Covert"),
    "M4A4 | Royal Paladin": ("Chroma 2", "Classified"),
    "M4A4 | Desolate Space": ("Chroma 3", "Classified"),
    "M4A4 | The Emperor": ("Ancient", "Covert"),
    "M4A4 | Neo-Noir": ("Clutch", "Classified"),
    "M4A4 | Hellfire": ("Cache", "Classified"),
    "M4A4 | Buzz Kill": ("Spectrum", "Classified"),
    "M4A4 | 龍王 (Dragon King)": ("Cache", "Covert"),
    "M4A4 | X-Ray": ("Revolver", "Classified"),
    "M4A4 | Temukau": ("Kilowatt", "Classified"),

    # M4A1-S Skins
    "M4A1-S | Knight": ("Chroma", "Classified"),
    "M4A1-S | Hot Rod": ("Falchion", "Classified"),
    "M4A1-S | Hyper Beast": ("Falchion", "Covert"),
    "M4A1-S | Golden Coil": ("Shadow", "Covert"),
    "M4A1-S | Chantico's Fire": ("Chroma 2", "Classified"),
    "M4A1-S | Player Two": ("Horizon", "Classified"),
    "M4A1-S | Printstream": ("CS20", "Covert"),
    "M4A1-S | Blue Phosphor": ("Fracture", "Classified"),
    "M4A1-S | Cyrex": ("Vanguard", "Classified"),
    "M4A1-S | Icarus Fell": ("Operation Bloodhound", "Restricted"),
    "M4A1-S | Mecha Industries": ("Gamma 2", "Classified"),
    "M4A1-S | Decimator": ("Spectrum 2", "Restricted"),

    # AWP Skins
    "AWP | Dragon Lore": ("Cobblestone", "Covert"),
    "AWP | Lightning Strike": ("Arms Deal", "Classified"),
    "AWP | Asiimov": ("Operation Phoenix", "Covert"),
    "AWP | Hyper Beast": ("Falchion", "Covert"),
    "AWP | Redline": ("Winter Offensive", "Classified"),
    "AWP | Electric Hive": ("eSports 2013", "Classified"),
    "AWP | Man-o'-war": ("Cobblestone", "Classified"),
    "AWP | Chromatic Aberration": ("Prisma", "Classified"),
    "AWP | Fade": ("Italy", "Classified"),
    "AWP | Gungnir": ("Norse", "Covert"),
    "AWP | The Prince": ("Mirage", "Covert"),
    "AWP | Containment Breach": ("Fracture", "Classified"),
    "AWP | Neo-Noir": ("Clutch", "Covert"),
    "AWP | Oni Taiji": ("Operation Hydra", "Covert"),
    "AWP | Wildfire": ("Chroma", "Classified"),
    "AWP | BOOM": ("eSports 2013", "Restricted"),

    # Glock-18 Skins
    "Glock-18 | Fade": ("Arms Deal", "Restricted"),
    "Glock-18 | Water Elemental": ("Breakout", "Classified"),
    "Glock-18 | Twilight Galaxy": ("Chroma", "Classified"),
    "Glock-18 | Neo-Noir": ("Clutch", "Restricted"),
    "Glock-18 | Vogue": ("Prisma", "Restricted"),
    "Glock-18 | Moonrise": ("Horizon", "Restricted"),
    "Glock-18 | Dragon Tattoo": ("eSports 2013", "Restricted"),
    "Glock-18 | Wasteland Rebel": ("Phoenix", "Restricted"),
    "Glock-18 | Bullet Queen": ("Shattered Web", "Classified"),

    # USP-S Skins
    "USP-S | Kill Confirmed": ("Shadow", "Classified"),
    "USP-S | Neo-Noir": ("Clutch", "Classified"),
    "USP-S | Orion": ("Winter Offensive", "Classified"),
    "USP-S | Cortex": ("Spectrum 2", "Classified"),
    "USP-S | Printstream": ("CS20", "Restricted"),
    "USP-S | The Traitor": ("Broken Fang", "Restricted"),
    "USP-S | Caiman": ("Phoenix", "Restricted"),
    "USP-S | Serum": ("Huntsman", "Restricted"),

    # Desert Eagle Skins
    "Desert Eagle | Blaze": ("Arms Deal", "Restricted"),
    "Desert Eagle | Printstream": ("CS20", "Classified"),
    "Desert Eagle | Code Red": ("Chroma 3", "Classified"),
    "Desert Eagle | Kumicho Dragon": ("Chroma 2", "Covert"),
    "Desert Eagle | Cobalt Disruption": ("Spectrum", "Restricted"),
    "Desert Eagle | Mecha Industries": ("Gamma 2", "Restricted"),
    "Desert Eagle | Hypnotic": ("Arms Deal", "Classified"),
    "Desert Eagle | Golden Koi": ("Breakout", "Restricted"),
    "Desert Eagle | Conspiracy": ("Phoenix", "Classified"),

    # P250 Skins
    "P250 | See Ya Later": ("Broken Fang", "Classified"),
    "P250 | Asiimov": ("Cache", "Classified"),
    "P250 | Nuclear Threat": ("Industrial", "Restricted"),
    "P250 | Muertos": ("Chroma", "Restricted"),
    "P250 | Undertow": ("Shadow", "Restricted"),
    "P250 | Whiteout": ("Winter Offensive", "Restricted"),
    "P250 | Cartel": ("Huntsman", "Restricted"),
    "P250 | Franklin": ("Huntsman", "Industrial Grade"),

    # Five-SeveN Skins
    "Five-SeveN | Case Hardened": ("Arms Deal", "Restricted"),
    "Five-SeveN | Hyper Beast": ("Falchion", "Restricted"),
    "Five-SeveN | Monkey Business": ("Chroma 2", "Restricted"),
    "Five-SeveN | Fowl Play": ("Vanguard", "Restricted"),
    "Five-SeveN | Copper Galaxy": ("Chroma", "Restricted"),
    "Five-SeveN | Retrobution": ("Spectrum", "Restricted"),

    # Tec-9 Skins
    "Tec-9 | Fuel Injector": ("Glove", "Restricted"),
    "Tec-9 | Nuclear Threat": ("Industrial", "Restricted"),
    "Tec-9 | Bamboozle": ("Spectrum", "Restricted"),
    "Tec-9 | Titanium Bit": ("Phoenix", "Restricted"),
    "Tec-9 | Red Quartz": ("Huntsman", "Restricted"),
    "Tec-9 | Ice Cap": ("Breakout", "Restricted"),

    # CZ75-Auto Skins
    "CZ75-Auto | The Fuschia Is Now": ("Chroma 3", "Restricted"),
    "CZ75-Auto | Red Astor": ("Revolver", "Restricted"),
    "CZ75-Auto | Emerald Quartz": ("Falchion", "Restricted"),
    "CZ75-Auto | Victoria": ("Huntsman", "Classified"),
    "CZ75-Auto | Chalice": ("Chroma", "Restricted"),
    "CZ75-Auto | Xiangliu": ("Spectrum 2", "Restricted"),

    # R8 Revolver Skins
    "R8 Revolver | Fade": ("Gamma", "Restricted"),
    "R8 Revolver | Llama Cannon": ("Gamma", "Classified"),
    "R8 Revolver | Amber Fade": ("Revolver", "Restricted"),
    "R8 Revolver | Crimson Web": ("Revolver", "Restricted"),
    "R8 Revolver | Survivalist": ("Spectrum", "Mil-Spec Grade"),
    "R8 Revolver | Grip": ("Glove", "Mil-Spec Grade"),

    # MAC-10 Skins
    "MAC-10 | Neon Rider": ("Falchion", "Restricted"),
    "MAC-10 | Heat": ("Arms Deal", "Restricted"),
    "MAC-10 | Disco Tech": ("Horizon", "Restricted"),
    "MAC-10 | Curse": ("Huntsman", "Restricted"),
    "MAC-10 | Fade": ("Italy", "Restricted"),
    "MAC-10 | Stalker": ("Operation Hydra", "Restricted"),

    # MP9 Skins
    "MP9 | Hypnotic": ("Arms Deal", "Restricted"),
    "MP9 | Hot Rod": ("Falchion", "Restricted"),
    "MP9 | Starlight Protector": ("Horizon", "Restricted"),
    "MP9 | Bulldozer": ("Phoenix", "Restricted"),
    "MP9 | Rose Iron": ("Huntsman", "Restricted"),
    "MP9 | Wild Lily": ("Chroma 2", "Restricted"),

    # MP7 Skins
    "MP7 | Nemesis": ("Vanguard", "Restricted"),
    "MP7 | Fade": ("Italy", "Restricted"),
    "MP7 | Bloodsport": ("Spectrum", "Restricted"),
    "MP7 | Whiteout": ("Winter Offensive", "Restricted"),
    "MP7 | Skulls": ("Phoenix", "Restricted"),
    "MP7 | Impire": ("Chroma 3", "Restricted"),

    # UMP-45 Skins
    "UMP-45 | Primal Saber": ("Chroma", "Restricted"),
    "UMP-45 | Arctic Wolf": ("Winter Offensive", "Restricted"),
    "UMP-45 | Momentum": ("Horizon", "Restricted"),
    "UMP-45 | Blaze": ("Vanguard", "Restricted"),
    "UMP-45 | Crime Scene": ("Shadow", "Restricted"),
    "UMP-45 | Grand Prix": ("Chroma 3", "Restricted"),

    # P90 Skins
    "P90 | Asiimov": ("Operation Phoenix", "Classified"),
    "P90 | Death by Kitty": ("eSports 2014", "Classified"),
    "P90 | Dragon King": ("Cache", "Restricted"),
    "P90 | Emerald Dragon": ("Train", "Classified"),
    "P90 | Trigon": ("Breakout", "Restricted"),
    "P90 | Cold Blooded": ("Shadow", "Restricted"),
    "P90 | Shallow Grave": ("Spectrum 2", "Restricted"),
    "P90 | Nostalgia": ("Prisma", "Restricted"),

    # PP-Bizon Skins
    "PP-Bizon | Judgement of Anubis": ("Anubis", "Classified"),
    "PP-Bizon | High Roller": ("Chroma 2", "Restricted"),
    "PP-Bizon | Fuel Rod": ("Gamma", "Restricted"),
    "PP-Bizon | Antique": ("Dust 2", "Restricted"),
    "PP-Bizon | Blue Streak": ("Arms Deal", "Restricted"),
    "PP-Bizon | Osiris": ("Gods and Monsters", "Restricted"),

    # Additional weapons can be added here following the same pattern...
}

# Utility function to get skin info
def get_skin_info(skin_name: str) -> tuple:
    """
    Get collection and rarity for a skin
    Returns: (collection, rarity) or (None, None) if not found
    """
    return ENHANCED_WEAPON_SKIN_MAPPINGS.get(skin_name, (None, None))

# Function to merge with existing mappings
def merge_with_existing_mappings():
    """
    This function can be used to merge these mappings with the existing skin_mapping.py
    """
    return ENHANCED_WEAPON_SKIN_MAPPINGS
